import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FormButtonsDesktop } from "./ui/desktop/FormButtonsDesktop";
import { FormButtonsMobile } from "./ui/mobile/FormButtonsMobile";
import { FormStepsMobile } from "./ui/mobile/FormStepsMobile";
import { FormStepsDesktop } from "./ui/desktop/FormStepsDektop";

const ubuntuBold = localFont({
  src: "./util/fonts/Ubuntu-Bold.ttf",
  variable: "--font-ubuntu-bold",
});
const ubuntuMedium = localFont({
  src: "./util/fonts/Ubuntu-Medium.ttf",
  variable: "--font-ubuntu-medium",
});
const ubuntuRegular = localFont({
  src: "./util/fonts/Ubuntu-Regular.ttf",
  variable: "--font-ubuntu-regular"
});

export const metadata: Metadata = {
  title: {
    template: '%s | Multi step',
    default: 'Multi step',
  },
  description: "Mulit step form generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuRegular.variable} ${ubuntuMedium.variable} ${ubuntuBold.variable} antialiased`}
      >
        <div className="flex flex-col h-[100vh] overflow-hidden md:bg-magnolia">
          {/* Mobile BG Image */}
          <div className="md:hidden absolute top-0 left-0 w-full h-[20%] bg-center z-[-20] bg-[url('/bg-sidebar-mobile.svg')] bg-no-repeat bg-cover"/>
          <main className="flex-grow p-4">
            {/* Grid for desktop */}
            <div className="h-screen md:grid md:items-center md:grid-cols-12 md:gap-4">
              <div className="flex flex-row justify-between md:col-span-12 p-4 bg-white rounded-xl shadow-xl h-[80vh]">
                {/* Desktop steps */}
                <FormStepsDesktop />
                {/* Mobile steps */}
                <FormStepsMobile />

                <div className="flex flex-col justify-between w-[100%] pt-14 pr-28 pb-4 pl-28">
                  {/* Form Content */}
                  {children}
                  {/* Desktop Next and Go Back buttons */}
                  <FormButtonsDesktop />
                </div>
              </div>
            </div>
          </main>

          {/* Mobile Next and Go Back buttons */}
          <FormButtonsMobile />
        </div>
      </body>
    </html>
  );
}
