import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FormButtonsDesktop } from "./ui/desktop/FormButtonsDesktop";
import { FormButtonsMobile } from "./ui/mobile/FormButtonsMobile";
import { FormStepsMobile } from "./ui/mobile/FormStepsMobile";
import { FormStepsDesktop } from "./ui/desktop/FormStepsDektop";

const ubuntuBold = localFont({
  src: "./fonts/Ubuntu-Bold.ttf",
  variable: "--font-ubuntu-bold",
});
const ubuntuMedium = localFont({
  src: "./fonts/Ubuntu-Medium.ttf",
  variable: "--font-ubuntu-medium",
});
const ubuntuRegular = localFont({
  src: "./fonts/Ubuntu-Regular.ttf",
  variable: "--font-ubuntu-regular"
});

export const metadata: Metadata = {
  title: {
    template: '%s | Multi step',
    default: 'Multi step',
  },
  description: "Mulit step form generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuRegular.variable} ${ubuntuMedium.variable} ${ubuntuBold.variable} antialiased`}
      >
        <div className="flex flex-col">
          {/* Mobile BG Image */}
          <div className="md:hidden absolute top-0 left-0 w-full h-[30%] bg-center z-[-20] bg-[url('/bg-sidebar-mobile.svg')] bg-no-repeat bg-cover"/>
          <main className="flex-grow p-4">
            {/* Grid for desktop */}
            <div className="h-screen md:grid md:grid-cols-12 md:gap-4 md:h-[97vh]">
              {/* Desktop steps */}
              <FormStepsDesktop />
              {/* Mobile steps */}
              <FormStepsMobile />

              {/* Form Content */}
              <div className="md:col-span-8 p-6 bg-white rounded-xl shadow-md flex flex-col justify-between h-auto">
                {children}
                {/* Desktop Next and Go Back buttons */}
                <FormButtonsDesktop />
              </div>
            </div>
          </main>

          {/* Mobile Next and Go Back buttons */}
          <FormButtonsMobile />
        </div>
      </body>
    </html>
  );
}
